// ignore_for_file: constant_identifier_names, camel_case_types

enum APPLICATION_COLOR {
  TITLE,
  SUBTITLE,
  BACKGROUND,
  LIGHT,
  DARK,
  PRIMARY,
  SECONDARY,
  OPPOSITE
}

enum FONT_SIZE {
  DISPLAY_LARGE,
  DISPLAY_MEDIUM,
  DISPLAY_SMALL,
  HEADLINE_LARGE,
  HEADLINE_MEDIUM,
  HEADLINE_SMALL,
  TITLE_LARGE,
  TITLE_MEDIUM,
  TITLE_SMALL,
  BODY_LARGE,
  BODY_MEDIUM,
  BODY_SMALL,
  LABEL_LARGE,
  LABEL_MEDIUM,
  LABEL_SMALL,
}
